name: PXXL Keep-Alive

on:
  schedule:
    # Run every 2 hours
    - cron: '0 */2 * * *'
  workflow_dispatch: {}

jobs:
  ping_render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /cron endpoint
        env:
          CRON_URL: ${{ secrets.CRON_URL }}
        run: |
          if [ -z "$CRON_URL" ]; then
            echo "CRON_URL not set in secrets"
            exit 1
          fi

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$CRON_URL" --fail)
          echo "PXXL keepalive returned $HTTP_STATUS"
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "PXXL keepalive failed with status $HTTP_STATUS" >&2
            exit 1
          fi